# Generated by Django 3.0.3 on 2020-04-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grancum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ՄյուսՄասնագետներ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ամսաթիվը', models.DateField(verbose_name='Ամսաթիվը')),
                ('ՀետազոտմանՏվյալներ', models.TextField(max_length=1000, verbose_name='ՀետազոտմանՏվյալներ')),
                ('հհ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում')),
            ],
        ),
    ]
