# Generated by Django 3.0.3 on 2020-04-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grancum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ֆիզիկական',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ամսաթիվը', models.DateField(blank=True, null=True, verbose_name='Ամսաթիվը')),
                ('Քաշը', models.IntegerField(blank=True, help_text='կգ', null=True, verbose_name='Քաշը')),
                ('Հասակը', models.IntegerField(blank=True, help_text='սմ', null=True, verbose_name='Հասակը')),
                ('ԿրծքավանդակիՇրջանագիծըՀանգիստ', models.BigIntegerField(blank=True, help_text='սմ', null=True, verbose_name='ԿրծքավանդակիՇրջանագիծըՀանգիստ')),
                ('ԿրծքավանդակիՇրջանագիծըՇնչելիս', models.BigIntegerField(blank=True, help_text='սմ', null=True, verbose_name='ԿրծքավանդակիՇրջանագիծըՇնչելիս')),
                ('ԿրծքավանդակիՇրջանագիծըԱրտաշնչելիս', models.BigIntegerField(blank=True, help_text='սմ', null=True, verbose_name='ԿրծքավանդակիՇրջանագիծըԱրտաշնչելիս')),
                ('ՓորիՇրջագիծը', models.BigIntegerField(blank=True, null=True, verbose_name='ՓորիՇրջագիծը')),
                ('Շնչաչափը', models.BigIntegerField(blank=True, null=True, verbose_name='Շնչաչափը')),
                ('ՁեռքիՈՒժաչափըԱջ', models.BigIntegerField(blank=True, null=True, verbose_name='ՁեռքիՈՒժաչափըԱջ')),
                ('ՁեռքիՈՒժաչափըՁախ', models.BigIntegerField(blank=True, null=True, verbose_name='ՁեռքիՈՒժաչափըՁախ')),
                ('հհ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում')),
            ],
        ),
    ]
